### ISSUE TITLE
requrements extendable to Neos/Flow ^6.0? 

### ISSUE THREAD

**Issue by penkyhurk** [onivaevents/Swisscom.SimpleSamlServiceProvider#2]
It would be nice if this package also would be available for Neos/Flow version 6.0 and above...

**Comment by simstern** [comment]
This will come some time next year. The driving project of this package is still running on `neos/flow` v5 at the moment.
Anyway, I'm happy to get a PR with the required changes ;-)

**Comment by simstern** [comment]
Fixed with v2.0
