### ISSUE TITLE
Issue in SamlToken->updateCredentials

### ISSUE THREAD

**Issue by penkyhurk** [onivaevents/Swisscom.SimpleSamlServiceProvider#3]
Found an issue in 
Swisscom\SimpleSamlServiceProvider\Security\Authentication\Token\SamlToken.php
function updateCredentials:

In case of 'username' is not provided in array $attributes the else case sets `$this->credentials['username'] = $nameId->getValue();`
(line 60).

This fails due to Class `\SAML2\XML\saml\NameID` does not have any methods and ancestors don't have a getter named `getValue()`.
Of course this case seems to be rare ;-)

**Comment by simstern** [comment]
Thanks for the report. The accessibility of `NameID` properties has change in v3 of `simplesamlphp/saml2` which is only required since v1.17 of `simplesamlphp/simplesamlphp`. I therfore changed the miniumum requirements which should fix that.
